# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tascii < Formula
  desc "A fast, minimal terminal task manager with priorities and deadlines."
  homepage "https://github.com/walid-idrissi-labs/tascii"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/walid-idrissi-labs/tascii/releases/download/v1.0.1/tascii_darwin_amd64.tar.gz"
      sha256 "5cd391bd6e965752b42e480eda562b32ae7a14da87098bd88aeb7778fa7e73e1"

      define_method(:install) do
        bin.install "tascii"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/walid-idrissi-labs/tascii/releases/download/v1.0.1/tascii_darwin_arm64.tar.gz"
      sha256 "23e256bffea5c8625373f48178812ab206286640f2dc1dd045087f585400c83f"

      define_method(:install) do
        bin.install "tascii"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/walid-idrissi-labs/tascii/releases/download/v1.0.1/tascii_linux_amd64.tar.gz"
      sha256 "7c75a8b9b17dd1852014ce7ea09701b3b51e7a652729432859635deffecad057"
      define_method(:install) do
        bin.install "tascii"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/walid-idrissi-labs/tascii/releases/download/v1.0.1/tascii_linux_arm64.tar.gz"
      sha256 "99b09eb75be53b977e6aa5fe24b79859a730f24fd785be4e8a68f9ba7efac7a7"
      define_method(:install) do
        bin.install "tascii"
      end
    end
  end

  test do
    system "#{bin}/tascii --version"
  end
end
